### ISSUE TITLE
Cannot get bones

### ISSUE THREAD

**Issue by Megapon** [Sh1nyLabs/Bones-update#1]
Skeletons are just become a pile of bones and no loot drops, then they are reborn and all over again

**Comment by Theranius** [comment]
I confirm this, even when we burn the pile of bones we get nada, and that's the same for experience.

**Comment by Megapon** [comment]
> I confirm this, even when we burn the pile of bones we get nada, and that's the same for experience.

Oh, thanks, I just didn't find any video about your mod, which is strange, since it's really very good

**Comment by Megapon** [comment]
> Я подтверждаю это, даже когда мы сжигаем кучу костей, мы ничего не получаем, и то же самое касается опыта.

But I'm still interested in how to get loot from skeletons?

**Comment by Sh1nyLabs** [comment]
Hello Megapon and Theranius, 

In this mod, skeletons are intended to be harder to beat and loot. The fact that they no more drop experience or loot is intended by this mod mecanics. When beaten, they become **broken** and  will revive indefinitely.

In order to get loot from skeletons, you shall 'purify' them with an **Amulet** (use it on the broken skeleton). It is only after this that you will get loot and experience. 

You can **craft an Amulet** after looting a **Necromancer** (findable in custom structures, or in Raids if you are not using **forge 1.20.6**)


We hope that those informations will help you to enjoy the mod. Thanks for the support, it motivates us to keep developing and porting the mod for latest minecraft version!
